# Generated by Django 4.0.4 on 2022-06-18 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_blog_event_testomonials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Events',
        ),
    ]
