# Generated by Django 4.0.4 on 2022-06-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_blog_title_alter_events_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name_plural': 'Events'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.CharField(max_length=255, null=True, verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_time',
            field=models.CharField(max_length=255, null=True, verbose_name='Event Time'),
        ),
        migrations.AlterField(
            model_name='events',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
