# Generated by Django 4.0.4 on 2022-06-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_imagecategory_alter_testomonials_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecategory',
            name='image',
            field=models.ImageField(null=True, upload_to='image_category/', verbose_name='Image'),
        ),
    ]
