# Generated by Django 4.0.4 on 2022-08-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_ourpartner_alter_slider_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PopularCourse',
            new_name='ThreeZero',
        ),
        migrations.AlterModelOptions(
            name='threezero',
            options={'verbose_name_plural': 'Three Zeros'},
        ),
    ]
