# Generated by Django 4.0.4 on 2022-08-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'On Going')], max_length=50, verbose_name='Status'),
        ),
    ]
