# Generated by Django 4.0.4 on 2022-08-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_outcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('files', models.FileField(max_length=200, upload_to='annualreport/')),
            ],
        ),
    ]
