# Generated by Django 4.0.4 on 2022-08-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_annualreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreport',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='annualreport_images/'),
        ),
    ]
