# Generated by Django 4.0.4 on 2022-08-24 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_annualreport_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='News',
        ),
    ]
