# Generated by Django 4.0.4 on 2022-08-28 05:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='about/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'VISION, MISSION & STRATEGY',
            },
        ),
        migrations.AlterModelOptions(
            name='keyachievement',
            options={'verbose_name_plural': 'Key and Achievement'},
        ),
        migrations.AlterField(
            model_name='keyachievement',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='fullname',
            field=models.CharField(max_length=225, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.CharField(choices=[('team', 'Team Member'), ('board', 'Board Member'), ('both', 'Both')], max_length=225),
        ),
    ]
