# Generated by Django 4.0.4 on 2022-08-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_mission_alter_keyachievement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'verbose_name_plural': 'Vision, Mission & Strategy'},
        ),
        migrations.RemoveField(
            model_name='outcome',
            name='image',
        ),
        migrations.RemoveField(
            model_name='outcome',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='outcome',
            name='title',
        ),
        migrations.AlterField(
            model_name='outcome',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
