# Generated by Django 4.0.4 on 2022-08-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_mission_options_remove_outcome_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='description',
            field=models.TextField(verbose_name='Write about Outcome'),
        ),
    ]
