# Generated by Django 4.0.4 on 2022-09-01 14:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_facility_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurPartnerDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Name')),
                ('tagline', models.CharField(max_length=255, verbose_name='Tag Line')),
                ('description', ckeditor.fields.RichTextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Our Partner Description',
            },
        ),
    ]
