# Generated by Django 4.0.4 on 2022-09-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_team_facebook_team_linkedin_alter_team_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.CharField(blank=True, max_length=245, null=True)),
                ('facebook', models.CharField(blank=True, max_length=245, null=True)),
                ('twitter', models.CharField(blank=True, max_length=245, null=True)),
                ('instagram', models.CharField(blank=True, max_length=245, null=True)),
            ],
        ),
    ]
